name: Release helm chart

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true

permissions: read-all

jobs:
  release-chart:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: "Extract Version"
        id: extract_version
        run: |
          if [ -n "${{ github.event.inputs.version }}" ]; then
            VERSION="${{ github.event.inputs.version }}"
          else
            GIT_TAG=${GITHUB_REF##*/}
            VERSION=${GIT_TAG##v}
          fi
          echo "::set-output name=version::$(echo $VERSION)"
      - name: Publish Helm chart
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.HELM_TOKEN }}
          charts_dir: helm
          charts_url: https://helm.strrl.dev
          owner: strrl
          repository: helm.strrl.dev
          branch: gh-pages
          app_version: ${{ steps.extract_version.outputs.version }}
          chart_version: ${{ steps.extract_version.outputs.version }}
